### ISSUE TITLE
JWT Authentication 

### ISSUE THREAD

**Issue by deekshu25** [hemanth-0007/NITCONF_Module_1_team5#28]
# About JWT
When a user successfully logs in, the backend server generates a JWT containing information about the user
The JWT is signed using a secret key known only to the server. This signature ensures the integrity of the token and allows the server to verify
The client typically stores the JWT, often in a secure manner such as in an HTTP-
The backend server verifies the JWT's signature using the secret key. 

This is to be implemented by adding 

- JWT configuration file 
- AuthController.java corresponding to this JWT 
- Authentication Service

**Comment by Mohan-227** [comment]
Its been done in the latest commit of the backend branch
